name: "CI - Test Templates"
on:
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
      typo3: ${{ steps.filter.outputs.typo3 }}
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            typo3: ./**/typo3/**

  discover-variances:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.set-matrix.outputs.MATRIX }}
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    env:
      TEMPLATE_MATRIX_FILE: ${{ github.workspace }}/src/${{ matrix.templates }}/.github/workflow-matrix.yaml
    steps:
      - uses: actions/checkout@v3
      - name: Check file existence
        id: file_check
        run: |
          if [ -f "${{ env.TEMPLATE_MATRIX_FILE }}" ]; then
            echo "check_result=true" >> $GITHUB_OUTPUT
          else
            echo "check_result=false" >> $GITHUB_OUTPUT
          fi          
      - name: Enhance matrix for testing ${{ matrix.templates }}
        id: set-matrix
        run: |
          if [ "${{ steps.file_check.outputs.check_result }}" = "true" ]; then
            export mtmp=$(yq -o=json ${{ env.TEMPLATE_MATRIX_FILE }} | jq -a '.[] += {"template" : "${{matrix.templates}}" }')
            echo ${mtmp}
            echo "MATRIX=\'$mtmp\'" >> $GITHUB_OUTPUT
          else
            echo "MATRIX=${{ matrix.templates }}" >> $GITHUB_OUTPUT
          fi
  test:
    needs: [discover-variances]
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        config: ${{ fromJSON(needs.discover-variances.outputs.MATRIX) }}
        #templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
        include:
          - templates: typo3
            phpVersion: "8.5"
            database: mysql
            webserver: apache
          - templates: typo3
            phpVersion: "8.4"
            database: mariadb
            webserver: frankenphp
          - templates: typo3
            phpVersion: "8.3"
            database: postgresql
            webserver: apache
          - templates: typo3
            phpVersion: "8.2"
            database: sqlite
            webserver: frankenphp
      #jq -r '.[] | . += {"template" : "typo3" }' fruits.json
    steps:
      - uses: actions/checkout@v3
      - name: Check changes in ${{ matrix.templates }}
        if: ${{ ! contains(needs.detect-changes.outputs.templates, matrix.templates) }}
        run: |
          echo "::error ::No changes detected in ${{ matrix.templates }}. Skipping tests for this template."
      - name: Set up devcontainer config
        if: success()
        id: set_devcontainer_config
        run: |
          echo "DEVCONTAINER_CONFIG={\"phpVersion\": \"${{ matrix.phpVersion }}\", \"database\": \"${{ matrix.database }}\", \"webserver\": \"${{ matrix.webserver }}\"}" >> $GITHUB_OUTPUT
      - name: Smoke test for '${{ matrix.templates }}'
        if: success()
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
          config: "'${{ steps.set_devcontainer_config.outputs.DEVCONTAINER_CONFIG }}'"
          #config: ${{ fromJSON( matrix ) }}